### ISSUE TITLE
File RawGeneCounts

### ISSUE THREAD

**Issue by devenderarora** [amarinderthind/RNA-seq-tutorial-for-gene-differential-expression-analysis#1]
Hey, 
Nice tutorial..!! But it would be great if you provide RawGeneCounts.tsv file. That will help newbie to get update with the kind of input data look like.
Thanks 
Regards
Devender Arora

**Comment by amarinderthind** [comment]
Hi,  I have updated the "RawGeneCounts.tsv." There are minor changes in the main script as well. I hope it will help.

**Comment by devenderarora** [comment]
Indeed this will help a lot of researchers.
Thanks
