### ISSUE TITLE
typo in RNA-Seq-DGE.R

### ISSUE THREAD

**Issue by tealel** [amarinderthind/RNA-seq-tutorial-for-gene-differential-expression-analysis#2]
Line 177 has a typo where "Case1" should be "case1"

current code is:

contrasts.edgeR <- makeContrasts(Case1 - Control, levels=design.mat)    ##FirstC-SecondC ##Define 

and should be 

contrasts.edgeR <- makeContrasts(case1 - Control, levels=design.mat)    ##FirstC-SecondC ##Define

**Comment by amarinderthind** [comment]
corrected! thanks for bringing into notice
